// Autogenerated IPC server implementation.
// Command:  /home/work/devel/helenos/tools/ipc_generator.py ../../uspace/lib/c/../../../abi/protocol/test.txt uspace/lib/c/ipc_test.c uspace/lib/c/ipc_test.h
// Source timestamp:  2025-12-24 11:43:02.556459

#include <stddef.h>
#include <stdlib.h>
#include <ipc_b.h>

typedef struct test_instance_impl test_instance_impl_t;
typedef struct test_instance test_instance_t;
typedef struct test_instance_ops test_instance_ops_t;

struct test_instance_ops {
	size_t _sizeof;
	void (*_handle_message)(test_instance_impl_t *self, const ipc_message_t *msg);
	void (*_destroy)(test_instance_impl_t *self);
	errno_t (*hello)(test_instance_impl_t *self);
};

void test_instance_handle_message(test_instance_impl_t *self, const ipc_message_t *msg);

errno_t test_instance_hello(test_instance_t *self);
