// Autogenerated IPC server implementation.
// Command:  /home/work/devel/helenos/tools/ipc_generator.py ../../uspace/lib/c/../../../abi/protocol/test.txt uspace/lib/c/ipc_test.c uspace/lib/c/ipc_test.h
// Source timestamp:  2025-12-24 11:43:02.556459

#include "ipc_test.h"

#define method_present(ops, method) \
	(offsetof(typeof(*ops), method) + sizeof(ops->method) <= ops->_sizeof && ops->method)

enum test_instance_methods {
	_test_instance_op_undef,
	_test_instance_op_hello,
};

void test_instance_handle_message(test_instance_impl_t *self, const ipc_message_t *msg)
{
	test_instance_ops_t *ops = *(test_instance_ops_t **) self;
	
	bool dropped = msg->flags & IPC_MESSAGE_FLAG_OBJECT_DROPPED;
	bool auto = msg->flags & IPC_MESSAGE_FLAG_AUTOMATIC_MESSAGE;
	bool protocol_error = msg->flags & IPC_MESSAGE_FLAG_PROTOCOL_ERROR;
	
	if (protocol_error)
		return;
	
	if (auto) {
		if (dropped)
			ops->_destroy(self);
		return;
	}
	
	switch (ipcb_get_val_1(msg)) {
	
	// hello() -> errno_t
	case _test_instance_op_hello:
		{
			// TODO: check message type and detect protocol mismatch
			if (!method_present(ops, hello) {
				ipcb_answer_protocol_error(msg);
				break;
			}
			
			errno_t rc = ops->hello(self);
			ipcb_message_t answer = ipcb_start_answer(&msg, rc);
			ipcb_send_answer(&msg, answer);
			break;
		}
	default:
		ipcb_answer_protocol_error(msg);
	}
	
	if (dropped)
		ops->_destroy(self);
}

errno_t test_instance_hello(test_instance_t *self)
{
	ipc_message_t msg = {};
}
